use_frameworks!

platform :ios, '8.0'

target 'JRShare_Example' do
  pod 'JRShare', :path => '../'

  target 'JRShare_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
